In [3]:
import numpy as np

In [2]:
simple_list=[1,2,3]

In [3]:
np.array(simple_list)

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[5,6,7],[8,9,10]]

In [5]:
np.array(list_of_lists)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,21,6)

array([ 0,  6, 12, 18])

In [9]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [44]:
a=np.eye(8)

In [15]:
np.random.rand(3,2)

array([[0.1841225 , 0.58588718],
       [0.01014724, 0.39861851],
       [0.30623486, 0.19020634]])

In [49]:
np.random.randint(5,20,10)

array([13, 14, 12, 13, 15, 10, 13, 10, 16, 10])

In [36]:
sample_array=np.arange(40)

In [32]:
rand_array=np.random.randint(0,100)

In [37]:
sample_array.reshape(8,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [38]:
rand_array.argmin()

AttributeError: 'int' object has no attribute 'argmin'

In [39]:
sample_array.shape

(40,)

In [42]:
sample_array.reshape(2,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39]])

In [43]:
sample_array.dtype

dtype('int32')

In [47]:
A.T

array([13, 17,  6,  6, 18,  9,  8, 18, 19, 12])

In [6]:
sample_array=np.arange(10,21)

In [8]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
sample_array[8]

18

In [10]:
sample_array[2:5]

array([12, 13, 14])

In [15]:
sample_array[[2,5]]

array([12, 15])

In [20]:
sample_array[1:9]=100

In [21]:
sample_array

array([ 10, 100, 100, 100, 100, 100, 100, 100, 100,  19,  20])

In [22]:
sample_array=np.arange(10,21)

In [23]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
subset_sample_array=sample_array[0:7]

In [25]:
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [26]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
subset_sample_array[:] = 1001

In [28]:
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [29]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [30]:
copy_sample_array = sample_array.copy()

In [31]:
copy_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [32]:
copy_sample_array[:] = 2000

In [33]:
copy_sample_array

array([2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000])

In [36]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [43]:
sample_matrix=np.array(([1,2,3,7],[4,8,6,7],[8,9,3,12],[87,98,67,1]))

In [44]:
sample_matrix

array([[ 1,  2,  3,  7],
       [ 4,  8,  6,  7],
       [ 8,  9,  3, 12],
       [87, 98, 67,  1]])

In [45]:
sample_matrix[0,3]

7

In [50]:
sample_matrix[1]

array([4, 8, 6, 7])

In [51]:
sample_matrix=np.array(([1,2,3,7,9],[4,8,6,7,3],[8,9,3,12,4],[87,98,67,11,21],[23,34,56,78,87]))

In [52]:
sample_matrix

array([[ 1,  2,  3,  7,  9],
       [ 4,  8,  6,  7,  3],
       [ 8,  9,  3, 12,  4],
       [87, 98, 67, 11, 21],
       [23, 34, 56, 78, 87]])

In [54]:
sample_matrix[:,(3,1)]

array([[ 7,  2],
       [ 7,  8],
       [12,  9],
       [11, 98],
       [78, 34]])

In [55]:
sample_array=np.arange(1,31)

In [57]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [58]:
sample_array <10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [60]:
sample_array[sample_array <15]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
a=14

In [64]:
sample_array[sample_array <a]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [67]:
sample_array[sample_array<15] +sample_array [sample_array <15]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [70]:
sample_array*sample_array-sample_array*.923

array([7.70000e-02, 2.15400e+00, 6.23100e+00, 1.23080e+01, 2.03850e+01,
       3.04620e+01, 4.25390e+01, 5.66160e+01, 7.26930e+01, 9.07700e+01,
       1.10847e+02, 1.32924e+02, 1.57001e+02, 1.83078e+02, 2.11155e+02,
       2.41232e+02, 2.73309e+02, 3.07386e+02, 3.43463e+02, 3.81540e+02,
       4.21617e+02, 4.63694e+02, 5.07771e+02, 5.53848e+02, 6.01925e+02,
       6.52002e+02, 7.04079e+02, 7.58156e+02, 8.14233e+02, 8.72310e+02])

In [71]:
sample_array+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [72]:
10/sample_array

array([10.        ,  5.        ,  3.33333333,  2.5       ,  2.        ,
        1.66666667,  1.42857143,  1.25      ,  1.11111111,  1.        ,
        0.90909091,  0.83333333,  0.76923077,  0.71428571,  0.66666667,
        0.625     ,  0.58823529,  0.55555556,  0.52631579,  0.5       ,
        0.47619048,  0.45454545,  0.43478261,  0.41666667,  0.4       ,
        0.38461538,  0.37037037,  0.35714286,  0.34482759,  0.33333333])

In [73]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [74]:
sample_array+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [75]:
sample_array+2*3

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36])

In [76]:
np.max(sample_array)

30

In [77]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [78]:
np.min(sample_array)

1

In [79]:
np.argmax(sample_array)

29

In [80]:
np.argmin(sample_array)

0

In [81]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [84]:
array=np.random.randn(6,6)

In [85]:
array

array([[ 0.74208051,  0.65027195,  0.07694583, -0.78511673, -0.30742738,
        -1.81441108],
       [-1.3459894 ,  1.91616017,  0.36475325,  0.43224377,  0.58896896,
        -0.19902367],
       [ 1.26746094, -1.5373436 ,  0.00875437,  0.6428165 ,  0.20350268,
         0.57294626],
       [ 0.6388112 , -0.06389056, -2.28689159, -0.53571901, -0.69110174,
        -0.80461281],
       [-0.45360428, -0.07096197, -0.02469351,  0.67360331,  0.09198336,
        -0.15790186],
       [-0.19516908,  0.44611222, -0.19500002,  0.10092754, -0.09753774,
        -0.52873333]])

In [87]:
np.round(array,decimals=2)

array([[ 0.74,  0.65,  0.08, -0.79, -0.31, -1.81],
       [-1.35,  1.92,  0.36,  0.43,  0.59, -0.2 ],
       [ 1.27, -1.54,  0.01,  0.64,  0.2 ,  0.57],
       [ 0.64, -0.06, -2.29, -0.54, -0.69, -0.8 ],
       [-0.45, -0.07, -0.02,  0.67,  0.09, -0.16],
       [-0.2 ,  0.45, -0.2 ,  0.1 , -0.1 , -0.53]])

In [88]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [89]:
np.std(array)

0.8173976109085735

In [90]:
np.mean(array)

-0.07435518143227092

In [91]:
np.median(array)

-0.04429203483632125

In [92]:
np.mode(array)

AttributeError: module 'numpy' has no attribute 'mode'

In [98]:
sports = np.array(['cric','cric','golf','hockey'])

In [99]:
sports

array(['cric', 'cric', 'golf', 'hockey'], dtype='<U6')

In [100]:
np.unique(sports)

array(['cric', 'golf', 'hockey'], dtype='<U6')

In [101]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [102]:
simple_array = np.arange(0,20)

In [103]:
simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [105]:
np.save('sample_array',sample_array)

In [106]:
np.savez('2_arrays.npz',a=sample_array,b=simple_array)

In [107]:
np.load('sample_array.npy')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [108]:
archive=np.load('2_arrays.npz')

In [110]:
archive['a']

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [111]:
np.savetxt('text_file.txt',sample_array,delimiter=',')

In [115]:
np.loadtxt('text_file.txt',delimiter=',')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30.])