# NumPy Lab Exercises 

Solve the following questions in Lab to test your knowledge on NumPy Package!

#### Import NumPy package as np

In [2]:
import numpy as np

#### Create an array of 20 0's 

In [5]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### Create an array of 20 1's

In [6]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### Create an array containing 30 sixes

In [15]:
sample_array=np.ones((5,6))
sample_array
sample_array[:] =6
sample_array

array([[6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.]])

#### Create an array of integers starting from 21 until 31

In [21]:
sample_array=np.arange(21,32)
sample_array

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

#### Create an array of all even integers from 2 to 60

In [29]:
sample_array=np.arange(2,60,2)
sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

#### Create a 5x6 matrix with values ranging from 0 to 29

In [34]:
sample_array=np.arange(0,30)
sample_array
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

#### Create an identity matrix of shape 5x5

In [36]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Use NumPy to generate a random set of 10 numbers between 0 and 1

In [39]:
np.random.rand(3,2)

array([[0.36873657, 0.0289694 ],
       [0.18937321, 0.86272746],
       [0.08182798, 0.78040818]])

#### Use NumPy to generate an array of 15 random numbers sampled from a standard normal distribution

array([-1.92121346,  1.20121677, -0.68039747,  1.57650788,  0.11374393,
        1.26951135, -0.11675437, -1.07877313,  0.23743239, -0.46378391,
        0.0874328 ,  0.00382938, -0.38638032,  1.3771973 ,  0.93654124])

#### Create the following 5x10 matrix with the values using arange,reshape and arithmetic operators:

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ]])

#### Create an array of 30 linearly spaced points between 0 and 10:

array([  0.        ,   0.34482759,   0.68965517,   1.03448276,
         1.37931034,   1.72413793,   2.06896552,   2.4137931 ,
         2.75862069,   3.10344828,   3.44827586,   3.79310345,
         4.13793103,   4.48275862,   4.82758621,   5.17241379,
         5.51724138,   5.86206897,   6.20689655,   6.55172414,
         6.89655172,   7.24137931,   7.5862069 ,   7.93103448,
         8.27586207,   8.62068966,   8.96551724,   9.31034483,
         9.65517241,  10.        ])

## Numpy Indexing and Selections

Using the below given Matrix, generate the output for the below questions

In [15]:
simple_matrix = np.arange(1,101).reshape(10,10)
simple_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique

array([[81, 82, 83],
       [91, 92, 93]])

#### Retrieve the value 55 from the above matrix using index & selection technique

55

#### Retrieve the values from the 3rd column in the above matrix

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

#### Retrieve the values from the 4th row in the above matrix

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

#### Retrieve values from the 2nd & 4th rows in the above matrix

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

### Calculate the following values for the given matrix

#### Calculate sum of all the values in the matrix

5050

#### Calculate standard deviation of all the values in the matrix

28.866070047722118

#### Calculate the variance of all values in the matrix

833.25

#### Calculate the mean of all values in the matrix

50.5

### End of Lab Exercise - NumPy