In [1]:
import numpy as np

In [2]:
simple_list = [1,2,3]

In [5]:
np.array(simple_list)

array([1, 2, 3, 4])

In [10]:
list_of_lists = [[1,2,3], [4,5,6], [7,8,9]]

In [11]:
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

In [17]:
ed = np.zeros(100)

In [20]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [24]:
a = np.eye(5)

In [28]:
np.random.rand(3,2)

array([[0.81398014, 0.9660038 ],
       [0.94235619, 0.32227645],
       [0.86056674, 0.88678629]])

In [30]:
a = np.random.randn(2,3)

In [37]:
np.random.randint(5,20,10)

array([17, 19, 18, 16, 17, 11,  7, 13, 16, 13])

In [38]:
sample_array = np.arange(30)

In [40]:
rand_array = np.random.randint(0,100,20)

In [39]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [43]:
rand_array.argmin()

1

In [44]:
sample_array.shape

(30,)

In [47]:
sample_array.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [51]:
sample_array.reshape(2,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [52]:
sample_array.dtype

dtype('int32')

In [53]:
a.T

array([[-2.43080012, -0.73971129],
       [ 0.92517876,  0.88285972],
       [-0.77030014, -0.00478122]])

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [0]:
a.T

array([[ 0.5496091 , -0.54812681],
       [ 1.36442643, -0.12962563],
       [-0.61062758, -0.64242844]])

In [54]:
sample_array = np.arange(10,21)

In [0]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [55]:
sample_array[8]

18

In [57]:
sample_array[[3,5]]

array([13, 15])

In [58]:
sample_array[1:2] = 100

In [59]:
sample_array

array([ 10, 100,  12,  13,  14,  15,  16,  17,  18,  19,  20])

In [60]:
sample_array = np.arange(10,21)

In [61]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [66]:
sample_array = np.arange(10,21)
                        
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [0]:
subset_sample_array = sample_array[0:7]

subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [0]:
subset_sample_array[:]=1001

In [0]:
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [0]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [68]:
copy_sample_array = sample_array.copy()

In [69]:
copy_sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [70]:
copy_sample_array[:]=10
copy_sample_array

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [72]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [89]:
sample_matrix = np.array(([50,20,10,89], [24,23,21,32], [76,54,32,12], [98,6,4,3]))
sample_matrix

array([[50, 20, 10, 89],
       [24, 23, 21, 32],
       [76, 54, 32, 12],
       [98,  6,  4,  3]])

In [94]:
sample_matrix[1][3]

32

In [95]:
sample_matrix[0,3]

89

In [96]:
sample_matrix[3,:]

array([98,  6,  4,  3])

In [97]:
sample_matrix[3]

array([98,  6,  4,  3])

In [0]:
sample_matrix = np.array(([50,20,1,23,34], [24,23,21,32,34], [76,54,32,12,98], [98,6,4,3,67], [12,23,34,56,67]))

In [98]:
sample_matrix

array([[50, 20, 10, 89],
       [24, 23, 21, 32],
       [76, 54, 32, 12],
       [98,  6,  4,  3]])

In [99]:
sample_matrix[:,(1,3)]

array([[20, 89],
       [23, 32],
       [54, 12],
       [ 6,  3]])

In [100]:
sample_matrix[:,(3,1)]

array([[89, 20],
       [32, 23],
       [12, 54],
       [ 3,  6]])

In [101]:
sample_array=np.arange(1,31)

In [0]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [105]:
bool = sample_array < 10
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [106]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
sample_array[sample_array <10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
a=7

In [109]:
sample_array[sample_array < a]

array([1, 2, 3, 4, 5, 6])

In [113]:
sample_array + sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [120]:
sample_array / (sample_array+2)

array([0.33333333, 0.5       , 0.6       , 0.66666667, 0.71428571,
       0.75      , 0.77777778, 0.8       , 0.81818182, 0.83333333,
       0.84615385, 0.85714286, 0.86666667, 0.875     , 0.88235294,
       0.88888889, 0.89473684, 0.9       , 0.9047619 , 0.90909091,
       0.91304348, 0.91666667, 0.92      , 0.92307692, 0.92592593,
       0.92857143, 0.93103448, 0.93333333, 0.93548387, 0.9375    ])

In [121]:
10/sample_array

array([10.        ,  5.        ,  3.33333333,  2.5       ,  2.        ,
        1.66666667,  1.42857143,  1.25      ,  1.11111111,  1.        ,
        0.90909091,  0.83333333,  0.76923077,  0.71428571,  0.66666667,
        0.625     ,  0.58823529,  0.55555556,  0.52631579,  0.5       ,
        0.47619048,  0.45454545,  0.43478261,  0.41666667,  0.4       ,
        0.38461538,  0.37037037,  0.35714286,  0.34482759,  0.33333333])

In [122]:
sample_array + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [127]:
np.var(sample_array)
np.std(sample_array)

8.65544144839919

In [129]:
array = np.random.randn(6,6)

In [130]:
array

array([[ 0.04845067, -1.18038633,  0.42248254, -0.05142341, -1.36136725,
         0.30299401],
       [-1.61467526,  0.39075441,  0.93477948,  0.34784237, -0.44987272,
         1.20433602],
       [ 0.73730009, -0.77659995,  1.51468023,  0.05985163,  0.67273411,
         2.18419375],
       [-0.60661064,  0.43761342, -0.86829869,  1.16347973,  0.82150292,
        -1.3292336 ],
       [ 0.31553244,  0.43853917,  0.03258891, -0.25562482, -0.23951448,
        -0.06119374],
       [-1.56534486,  1.08126289, -0.04582116, -0.17316682, -0.32892551,
        -0.13508465]])

In [131]:
np.std(array)

0.8625649734732673

In [134]:
np.mean(array)

0.057438192237472804

In [137]:
sports = np.array(['golf', 'cric', 'fball', 'cric', 'cric', 'fooseball'])

np.unique(sports)

array(['cric', 'fball', 'fooseball', 'golf'], dtype='<U9')

In [138]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [139]:
simple_array = np.arange(0,20)

In [140]:
simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [147]:
np.save('sample_array', sample_array)

In [148]:
np.savez('2_arrays.npz', a=sample_array, b=simple_array)

In [145]:
np.load('sample_array.npy')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [156]:
archive = np.load('2_arrays.npz')

In [157]:
archive['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [155]:
np.savetxt('text_file.txt', sample_array,delimiter=',')

In [158]:
np.loadtxt('text_file.txt', delimiter=',')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30.])