In [1]:
import numpy as np

In [2]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
sample_array=np.arange(30)

In [8]:
sample_array.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [9]:
sample_array.shape

(30,)

In [11]:
sample_array.reshape (5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [12]:
sample_array.dtype

dtype('int32')

In [13]:
a = np.random.randn(2,3)

In [14]:
a.T

array([[-0.9422267 , -0.09328643],
       [ 0.48198782, -0.19459596],
       [ 1.03199673, -1.13385551]])

In [15]:
sample_array = np.arange(10,21)

In [16]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
sample_array[[4,6]]

array([14, 16])

In [20]:
sample_array[1:2] = 100

In [21]:
sample_array

array([ 10, 100,  12,  13,  14,  15,  16,  17,  18,  19,  20])