In [1]:
import numpy as np
import pandas as pd

In [8]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

In [10]:
demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [5]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

In [6]:
demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [7]:
demo_matrix[2,3]

39

In [11]:
demo_array = np.arange(10,21)

In [12]:
subset_demo_array = demo_array[0:7]

In [13]:
subset_demo_array[:]= 101

In [14]:
subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [15]:
test_array = [10, 11.5, 12, 13.5, 14,15]   

In [16]:
test_array

[10, 11.5, 12, 13.5, 14, 15]

In [24]:
test_array[2:3]

[12]

In [25]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [26]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]

In [27]:
np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [31]:
np.array['football']

TypeError: 'builtin_function_or_method' object is not subscriptable

In [37]:
demo_array=np.arange(0,10)

In [33]:
demo_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
demo_array <3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [35]:
demo_array[demo_array <6]

array([0, 1, 2, 3, 4, 5])

In [36]:
np.max(demo_array)

9

In [38]:
football = [24, 235, 34, 456, 65, 67]

In [39]:
football = (24, 23, 34, 46, 65, 67)

In [40]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

In [41]:
demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [43]:
demo_matrix[:,(1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [44]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

In [45]:
demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [46]:
demo_matrix[2,3]

39

In [47]:
test_array = [10, 11.5, 12, 13.5, 14,15]   

In [48]:
test_array

[10, 11.5, 12, 13.5, 14, 15]

In [55]:
test_array[2:3]

[12]

In [56]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [57]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]

In [58]:
np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [59]:
football = [24, 235, 34, 456, 65, 67]

In [60]:
f2ootball = (24, 23, 34, 46, 65, 67)

In [63]:
np.array(football)

array([ 24, 235,  34, 456,  65,  67])