In [2]:
import numpy as np

In [3]:
rand_array = np.random.randint(0,100,20)

In [7]:
rand_array

array([14, 42, 32, 50, 25, 38, 61, 65, 27, 86, 71, 45, 46, 12,  4, 90,  6,
       80, 48, 56])

In [8]:
sample_array = np.arange(10,20)

In [9]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
sample_array[3:7]

array([13, 14, 15, 16])

In [12]:
sample_array[4:7]

array([14, 15, 16])

In [13]:
sample_array[5:7]

array([15, 16])